apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: hongspace
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: lijahong
  password: 'github access token'
